In [5]:
sents = [['a', 'b', 'c', 'a', 'b', 'c'],
    ['d', 'e', 'f', 'g'],
        ['a', 'b', 'c'],
        ['a', 'b', 'c']]
pad_token = '0'

sents_len_list = max([len(s) for s in sents])

sents_padded = [s + [pad_token] * (sents_len_list - len(s)) for s in sents]
sents_padded

[['a', 'b', 'c', 'a', 'b', 'c'],
 ['d', 'e', 'f', 'g', '0', '0'],
 ['a', 'b', 'c', '0', '0', '0'],
 ['a', 'b', 'c', '0', '0', '0']]

In [10]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

sentences = ["i like dog", "i love coffee", "i hate milk", "you like cat", "you love milk", "you hate coffee"]
dtype = torch.float

"""
Word Processing
"""
word_list = list(set(" ".join(sentences).split()))
word_dict = {w: i for i, w in enumerate(word_list)}
number_dict = {i: w for i, w in enumerate(word_list)}
n_class = len(word_dict)
word_dict
number_dict
n_class

9

In [24]:
input1 = torch.randint(10, (2, 2, 3))
mat2 = torch.randint(10, (2, 3, 4))
print(input1)
print(mat2)
res = torch.bmm(input1, mat2)
res

tensor([[[2, 8, 4],
         [6, 1, 0]],

        [[1, 3, 6],
         [2, 8, 8]]])
tensor([[[9, 9, 7, 9],
         [5, 8, 8, 8],
         [4, 0, 9, 7]],

        [[2, 2, 5, 5],
         [2, 4, 4, 0],
         [0, 0, 2, 1]]])


tensor([[[ 74,  82, 114, 110],
         [ 59,  62,  50,  62]],

        [[  8,  14,  29,  11],
         [ 20,  36,  58,  18]]])

In [26]:
!python sanity_check.py 1d

Running Sanity Check for Question 1d: Encode
--------------------------------------------------------------------------------
enc_hiddens Sanity Checks Passed!
dec_init_state[0] Sanity Checks Passed!
dec_init_state[1] Sanity Checks Passed!
--------------------------------------------------------------------------------
All Sanity Checks Passed for Question 1d: Encode!
--------------------------------------------------------------------------------


[nltk_data] Downloading package punkt to C:\Users\Jun/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


'CUDA_VISIBLE_DEVICES'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
